### ISSUE TITLE
maintance issue

### ISSUE THREAD

**Issue by dafinoer** [rizki4106/cnnindonesia-news-api#1]
hi @rizki4106 
are this project still maintain?

**Comment by rizki4106** [comment]
Masih mas

**Comment by rizki4106** [comment]
Apakah terdapat error ?, jika memang begitu mohon lampirkan pesan errornya supaya saya perbaiki secepatnya
Terimakasih

**Comment by dafinoer** [comment]
iya, dapet error `504 Gateway Time-out`

**Comment by rizki4106** [comment]
Mohon maaf mas itu di karenakan kemampuan server yang masih terbatas untuk menangani request, saya akan usahakan untuk memindahkan servernya ke yang lebih memadai secepat mungkin.
Terimakasih
