### ISSUE TITLE
beda url. hasil json sama

### ISSUE THREAD

**Issue by abdullzz** [rizki4106/cnnindonesia-news-api#4]
code berjalan normal namun ketika dicoba endpoint internasional dan nasional hasilnya sama. setelah saya telusuri mungkin karena implementasi ajax pada web cnn

berikut reference saya https://stackoverflow.com/questions/59993290/why-are-different-urls-returning-the-same-page

mungkin boleh dipastikan apakah issue ini benar?
thanks

**Comment by abdullzz** [comment]
ok saya nemu kenapanya. jadi sebenernya repo ini cuma fetch data headline index aja. gabisa per kategori. karena library beautiful soup cuma bisa scrape static website 

bisa dilihat disini https://stackoverflow.com/a/58252897/7639174

**Comment by rizki4106** [comment]
Hi, bug nya sudah diatasi silahkan coba pull dari branch master
