### ISSUE TITLE
Akses semua berita not working

### ISSUE THREAD

**Issue by wiscaksono** [rizki4106/cnnindonesia-news-api#6]
![image](https://user-images.githubusercontent.com/63142229/191883172-78d752ea-b3d7-4c77-b759-d029485d4180.png)

**Comment by wiscaksono** [comment]
![image](https://user-images.githubusercontent.com/63142229/191883809-f3450c2c-d6e7-4506-b357-d6d7d156809f.png)

**Comment by suwidadi** [comment]
> ![image](https://user-images.githubusercontent.com/63142229/191883172-78d752ea-b3d7-4c77-b759-d029485d4180.png)

diganti link element class 'title' menjadi 'leading-normal' di code.py

it should work for the moment, but the site is gradually changing the element
